name: BuildHarmoneyOSDll
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: released

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build x86 Release
        shell: pwsh
        run: |
          .\BuildDll.ps1 x86

      - name: Build x64 Release
        shell: pwsh
        run: |
          .\BuildDll.ps1 x64